FROM python:3.9-slim

# copy local python scripts into container
WORKDIR /
ADD receive.py send.py requirements.txt /

# create virtualenv
RUN python3 venv . \
    && . bin/activate \
    && pip3 install -r requirements.txt \
    && pip3 list

ENV VIRTUAL_ENV=/
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

CMD ["python"]